"""
Module: departments.py
Description: This module defines the API routes for managing hospital departments.
"""

import uuid
from fastapi import APIRouter, Depends, HTTPException, status
from sqlmodel import Session, select, not_
from src.db.connection import get_session

# Use feature-local ORM and DTOs
from src.department.models import Department as DepartmentModel
from src.department.schemas import (
    DepartmentCreate,
    DepartmentRead,
)

router = APIRouter(
    prefix="/departments",
    tags=["Departments"]
)


@router.post("/", response_model=DepartmentRead, status_code=status.HTTP_201_CREATED)
async def create_department(department_data: DepartmentCreate, session: Session = Depends(get_session)):
    """Creates a new hospital department.

    The backend automatically generates the ID, timestamps, and sync metadata flags.
    """
    # Quick guard check to see if the department name already exists
    existing_dept = session.exec(
        select(DepartmentModel).where(
            DepartmentModel.name == department_data.name)
    ).first()

    if existing_dept:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"A department named '{department_data.name}' already exists."
        )

    # Create an ORM instance from the validated DTO
    department_row = DepartmentModel(name=department_data.name, code=department_data.code,
                                     backup_department_id=department_data.backup_department_id)

    # Add to session, commit, and refresh to load autogenerated fields
    session.add(department_row)
    session.commit()
    session.refresh(department_row)

    # DepartmentRead has orm_mode=True, so returning the ORM instance is fine
    return department_row


@router.get("/", response_model=list[DepartmentRead])
async def list_departments(session: Session = Depends(get_session)):
    """Retrieves all active, non-deleted hospital departments."""
    departments = session.exec(
        select(DepartmentModel).where(not_(DepartmentModel.is_deleted))
    ).all()
    return departments


@router.get("/{department_id}", response_model=DepartmentRead)
async def get_department(department_id: uuid.UUID, session: Session = Depends(get_session)):
    """Fetches a specific department by its UUID."""
    department = session.get(DepartmentModel, department_id)

    if not department or department.is_deleted:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Department not found."
        )

    return department
